import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Match, Prediction, LiveOdds } from '../types';
import { Calendar, TrendingUp, MapPin, Clock, Users, ArrowUpRight, ArrowDownRight, Minus, Download, FileText, Sparkles, Loader2 } from 'lucide-react';
import { TeamLogo } from './TeamLogo';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF with autoTable for TypeScript
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface MatchDisplayProps {
  match: Match;
  prediction?: Prediction | null;
  liveOdds?: LiveOdds | null;
  liveStatus?: { score: string; status: string } | null;
}

export const MatchDisplay: React.FC<MatchDisplayProps> = ({ match, prediction, liveOdds, liveStatus }) => {
  const [isExporting, setIsExporting] = React.useState(false);
  // Use live odds if available, otherwise fallback to prediction odds
  const currentOdds = liveOdds || (prediction ? prediction.odds : null);

  const handleExportPDF = async () => {
    if (!prediction) return;
    setIsExporting(true);
    try {
      const doc = new jsPDF();
      const primaryColor = [16, 185, 129]; // Emerald-500

      // Header
      doc.setFillColor(24, 24, 27); // Zinc-900
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('AI MATCH ANALYSIS', 105, 25, { align: 'center' });
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`${match.league.name} | ${match.date}`, 105, 32, { align: 'center' });

      // Match Info
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(16);
      doc.text(`${match.homeTeam.name} vs ${match.awayTeam.name}`, 105, 55, { align: 'center' });

      // Predicted Score Box
      doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.setLineWidth(1);
      doc.roundedRect(65, 65, 80, 30, 3, 3, 'D');
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('AI PREDICTED SCORE', 105, 75, { align: 'center' });
      
      doc.setFontSize(24);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.text(prediction.correctScore, 105, 88, { align: 'center' });

      // Details Table
      const details = [
        ['Market HDP', prediction.marketHdp, 'AI Suggestion', prediction.suggestedHdp],
        ['Over/Under', prediction.overUnder, 'Market O/U', prediction.marketOverUnder],
        ['BTTS', prediction.btts, 'Half-Time', prediction.halfTimeResult],
        ['Confidence', `${prediction.confidence}%`, 'Corners', prediction.corners]
      ];

      doc.autoTable({
        startY: 105,
        head: [['Metric', 'Value', 'Metric', 'Value']],
        body: details,
        theme: 'grid',
        headStyles: { fillColor: primaryColor },
        styles: { fontSize: 9, cellPadding: 5 }
      });

      let finalY = (doc as any).lastAutoTable.finalY;

      // Odds Table
      const oddsData = [
        ['Home', prediction.odds.home.toFixed(2)],
        ['Draw', prediction.odds.draw.toFixed(2)],
        ['Away', prediction.odds.away.toFixed(2)]
      ];

      doc.autoTable({
        startY: finalY + 10,
        head: [['Outcome', 'Odds (1X2)']],
        body: oddsData,
        theme: 'striped',
        headStyles: { fillColor: [63, 63, 70] }, // Zinc-700
        styles: { fontSize: 9 }
      });

      finalY = (doc as any).lastAutoTable.finalY;

      // Reasoning Section
      if (prediction.reasoning && prediction.reasoning.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('AI Reasoning & Analysis', 14, finalY + 15);
        
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        let yPos = finalY + 22;
        
        prediction.reasoning.forEach((point) => {
          const lines = doc.splitTextToSize(`• ${point}`, 180);
          doc.text(lines, 14, yPos);
          yPos += (lines.length * 5) + 2;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by AI Football Predictor', 105, 285, { align: 'center' });

      doc.save(`Analysis-${match.homeTeam.name}-vs-${match.awayTeam.name}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
    } finally {
      setIsExporting(false);
    }
  };

  const formatHdp = (hdp: string) => {
    const isHome = hdp.toLowerCase().includes('home');
    const isAway = hdp.toLowerCase().includes('away');
    const cleanValue = hdp.replace(/home|away/gi, '').trim();
    
    return (
      <div className="flex items-center gap-2">
        {(isHome || isAway) && (
          <span className={`text-[8px] font-black px-1.5 py-0.5 rounded uppercase tracking-tighter ${
            isHome ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/20' : 'bg-zinc-700 text-zinc-400 border border-white/5'
          }`}>
            {isHome ? 'Home' : 'Away'}
          </span>
        )}
        <span className="font-black">{cleanValue || hdp}</span>
      </div>
    );
  };

  return (
    <div className="relative overflow-hidden bg-gradient-to-br from-zinc-900 to-black border border-white/10 rounded-[2.5rem] p-8 md:p-12 shadow-2xl">
      {/* Background Accent */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 blur-[100px] -mr-32 -mt-32" />
      <div className="absolute bottom-0 left-0 w-64 h-64 bg-emerald-500/5 blur-[100px] -ml-32 -mb-32" />

      <div className="relative flex flex-col items-center gap-8">
        <div className="flex flex-col md:flex-row items-center gap-4 md:gap-8 px-5 py-4 bg-white/5 rounded-3xl border border-white/10 backdrop-blur-sm w-full md:w-auto">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-white/5 rounded-xl flex items-center justify-center p-2 border border-white/5">
              <img 
                src={match.league.logo} 
                alt={match.league.name} 
                className="w-full h-full object-contain"
                referrerPolicy="no-referrer"
              />
            </div>
            <div className="flex flex-col">
              <span className="text-xs font-black text-white uppercase tracking-[0.2em] leading-none mb-1.5">
                {match.league.name}
              </span>
              <div className="flex items-center gap-2 text-[10px] font-bold text-zinc-500 uppercase tracking-widest leading-none">
                <Calendar className="w-3 h-3 text-emerald-500" />
                {match.date}
              </div>
            </div>
          </div>

          {(prediction?.stadium || prediction?.startTime) && (
            <div className="hidden md:block w-px h-8 bg-white/10" />
          )}

          <div className="flex flex-wrap justify-center gap-4 md:gap-6">
            {prediction?.stadium && (
              <div className="flex items-center gap-2 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">
                <MapPin className="w-3 h-3 text-emerald-500" />
                {prediction.stadium}
              </div>
            )}
            {prediction?.startTime && (
              <div className="flex items-center gap-2 text-[10px] font-bold text-zinc-400 uppercase tracking-widest">
                <Clock className="w-3 h-3 text-emerald-500" />
                {prediction.startTime}
                <span className="text-[8px] font-black text-zinc-500 bg-white/5 px-1.5 py-0.5 rounded border border-white/5 ml-1">
                  {prediction.startTime.toLowerCase().includes('utc') ? 'UTC' : 'Local'}
                </span>
              </div>
            )}
          </div>
        </div>

        <div className="w-full flex items-center justify-between gap-4 md:gap-12">
          {/* Home Team */}
          <div className="flex-1 flex flex-col items-center gap-4 text-center">
            <TeamLogo 
              src={prediction?.enrichedTeams?.home.logo || match.homeTeam.logo} 
              alt={match.homeTeam.name} 
              size="lg"
              className="bg-white/5 rounded-3xl p-4 border border-white/5 shadow-inner overflow-hidden"
            />
            <div className="space-y-1">
              <h3 className="text-xl md:text-2xl font-black text-white uppercase tracking-tight">
                {match.homeTeam.name}
              </h3>
              {prediction?.enrichedTeams?.home.description && (
                <p className="text-[10px] text-zinc-500 font-medium uppercase tracking-widest line-clamp-1">
                  {prediction.enrichedTeams.home.description}
                </p>
              )}
            </div>
          </div>

          {/* VS */}
          <div className="flex flex-col items-center gap-2">
            {liveStatus ? (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex flex-col items-center gap-2"
              >
                <div className="px-3 py-1 bg-red-500/10 border border-red-500/20 rounded-full flex items-center gap-1.5">
                  <div className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
                  <span className="text-[10px] font-black text-red-500 uppercase tracking-widest">{liveStatus.status}</span>
                </div>
                <div className="text-5xl md:text-7xl font-black text-white tracking-tighter drop-shadow-[0_0_20px_rgba(255,255,255,0.2)]">
                  {liveStatus.score}
                </div>
                <div className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em]">Current Live Score</div>
              </motion.div>
            ) : prediction ? (
              <motion.div 
                initial={{ scale: 0.5, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                className="flex flex-col items-center"
              >
                <div className="text-5xl md:text-7xl font-black text-white tracking-tighter drop-shadow-[0_0_20px_rgba(16,185,129,0.3)]">
                  {prediction.correctScore}
                </div>
                <div className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.3em] mt-2">AI Predicted Score</div>
                
                <button
                  onClick={handleExportPDF}
                  disabled={isExporting}
                  className="mt-4 flex items-center gap-2 px-4 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/20 rounded-xl text-[10px] font-black text-emerald-500 uppercase tracking-widest transition-all active:scale-95 disabled:opacity-50"
                >
                  {isExporting ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <Download className="w-3 h-3" />
                  )}
                  Download Analysis PDF
                </button>
              </motion.div>
            ) : (
              <>
                <div className="text-4xl md:text-6xl font-black text-zinc-800 italic">VS</div>
                <div className="h-1 w-12 bg-emerald-500 rounded-full" />
              </>
            )}
          </div>

          {/* Away Team */}
          <div className="flex-1 flex flex-col items-center gap-4 text-center">
            <TeamLogo 
              src={prediction?.enrichedTeams?.away.logo || match.awayTeam.logo} 
              alt={match.awayTeam.name} 
              size="lg"
              className="bg-white/5 rounded-3xl p-4 border border-white/5 shadow-inner overflow-hidden"
            />
            <div className="space-y-1">
              <h3 className="text-xl md:text-2xl font-black text-white uppercase tracking-tight">
                {match.awayTeam.name}
              </h3>
              {prediction?.enrichedTeams?.away.description && (
                <p className="text-[10px] text-zinc-500 font-medium uppercase tracking-widest line-clamp-1">
                  {prediction.enrichedTeams.away.description}
                </p>
              )}
            </div>
          </div>
        </div>

        {currentOdds && (
          <div className="w-full mt-4 pt-8 border-t border-white/5">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-emerald-500" />
                <span className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em]">ហាងឆេងបច្ចុប្បន្ន 1X2</span>
              </div>
              {liveOdds && (
                <div className="flex items-center gap-2 px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-full">
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                  <span className="text-[10px] font-black text-emerald-500 uppercase tracking-widest">Live Feed</span>
                </div>
              )}
            </div>
            
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-white/5 rounded-2xl p-4 border border-white/5 flex flex-col items-center gap-1 group hover:bg-white/10 transition-colors relative">
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Home</span>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-black text-white">{currentOdds.home.toFixed(2)}</span>
                  {liveOdds?.change === 'up' && <ArrowUpRight className="w-3 h-3 text-emerald-500" />}
                  {liveOdds?.change === 'down' && <ArrowDownRight className="w-3 h-3 text-red-500" />}
                </div>
              </div>
              <div className="bg-white/5 rounded-2xl p-4 border border-white/5 flex flex-col items-center gap-1 group hover:bg-white/10 transition-colors">
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Draw</span>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-black text-white">{currentOdds.draw.toFixed(2)}</span>
                  {liveOdds?.change === 'up' && <ArrowUpRight className="w-3 h-3 text-emerald-500" />}
                  {liveOdds?.change === 'down' && <ArrowDownRight className="w-3 h-3 text-red-500" />}
                </div>
              </div>
              <div className="bg-white/5 rounded-2xl p-4 border border-white/5 flex flex-col items-center gap-1 group hover:bg-white/10 transition-colors">
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Away</span>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-black text-white">{currentOdds.away.toFixed(2)}</span>
                  {liveOdds?.change === 'up' && <ArrowUpRight className="w-3 h-3 text-emerald-500" />}
                  {liveOdds?.change === 'down' && <ArrowDownRight className="w-3 h-3 text-red-500" />}
                </div>
              </div>
            </div>

            {prediction && (
              <>
                <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="bg-emerald-500/5 rounded-2xl p-4 border border-emerald-500/10 flex flex-col items-center gap-1 relative overflow-hidden">
                    <div className="absolute top-0 right-0 bg-emerald-500 text-[8px] font-black px-2 py-0.5 rounded-bl-lg text-black uppercase tracking-tighter">Live Market</div>
                    <span className="text-[10px] font-bold text-emerald-500/60 uppercase tracking-widest">Market HDP</span>
                    <div className="text-lg text-emerald-400">{formatHdp(prediction.marketHdp)}</div>
                  </div>
                  <div className="bg-white/5 rounded-2xl p-4 border border-white/10 flex flex-col items-center gap-1">
                    <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">AI Suggestion</span>
                    <div className="text-lg text-white">{formatHdp(prediction.suggestedHdp)}</div>
                  </div>
                  <div className="bg-white/5 rounded-2xl p-4 border border-white/10 flex flex-col items-center gap-1">
                    <div className="flex items-center gap-1.5">
                      <Clock className="w-3 h-3 text-emerald-500" />
                      <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Half-Time Result</span>
                    </div>
                    <div className="text-lg text-white font-black uppercase tracking-tight">
                      {prediction.halfTimeResult}
                    </div>
                  </div>
                </div>

                {/* H2H Stats Section */}
                <div className="mt-8 pt-8 border-t border-white/5 w-full">
                  <div className="flex items-center justify-center gap-2 mb-6">
                    <Users className="w-4 h-4 text-emerald-500" />
                    <span className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em]">ស្ថិតិជួបគ្នា ១០ប្រកួតចុងក្រោយ (H2H)</span>
                  </div>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center gap-1">
                      <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Home Wins</span>
                      <div className="text-2xl font-black text-white">{prediction.h2h.homeWins}</div>
                      <div className="w-full h-1 bg-zinc-800 rounded-full mt-1 overflow-hidden">
                        <div 
                          className="h-full bg-emerald-500" 
                          style={{ width: `${(prediction.h2h.homeWins / 10) * 100}%` }} 
                        />
                      </div>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Draws</span>
                      <div className="text-2xl font-black text-white">{prediction.h2h.draws}</div>
                      <div className="w-full h-1 bg-zinc-800 rounded-full mt-1 overflow-hidden">
                        <div 
                          className="h-full bg-zinc-500" 
                          style={{ width: `${(prediction.h2h.draws / 10) * 100}%` }} 
                        />
                      </div>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Away Wins</span>
                      <div className="text-2xl font-black text-white">{prediction.h2h.awayWins}</div>
                      <div className="w-full h-1 bg-zinc-800 rounded-full mt-1 overflow-hidden">
                        <div 
                          className="h-full bg-white" 
                          style={{ width: `${(prediction.h2h.awayWins / 10) * 100}%` }} 
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </>
            )}
        </div>
      )}
    </div>
  </div>
);
};
